### ISSUE TITLE
Version 1.8 broke Visual Studio 2010 support

### ISSUE THREAD

**Issue by andreasmoegelmose** [einaregilsson/StopOnFirstBuildError#11]
When I try to install on Visual Studio 2010 (which my company is stuck at), I get the "The extension manifest is invalid." error. I suspect it is much the same error as https://github.com/einaregilsson/StopOnFirstBuildError/issues/7. Would it be possible for you to fix it again?

**Comment by einaregilsson** [comment]
Ok, that's probably caused by the new extension format for VS2017. I don't know if it's possible to support both with the same manifest. But VS2010 is 7 years old by now, I'm not really supporting it anymore. (I'm not really supporting anything anymore, I don't have a Windows machine or Visual Studio!). The patch for VS2017 was a pull request from someone else. Your best bet is probably to just install the old version again, from the VS gallery if possible, but otherwise just build it yourself. There are no new features in the latest version, just VS2017 support.

**Comment by andreasmoegelmose** [comment]
That's completely fair. I'll try and build it myself (and then start pushing for a migration to VS 2017).

**Comment by einaregilsson** [comment]
Cool, good luck :) You could also try to see if there's any way to download old versions from the VS gallery. I should probably start adding the releases to GitHub as well, so there's an easy way to get older versions.
