### ISSUE TITLE
New Install of VS2013 Cannot install latest version

### ISSUE THREAD

**Issue by mattritchie** [einaregilsson/StopOnFirstBuildError#16]
I have 1.8 installed on my older machine. 
If i could simply install that version i would.
Attempting to install into VS2013 Update 5 is not possible.

Are you still supporting this far back?
Any chance of getting access to older versions to run without support?

**Comment by einaregilsson** [comment]
I haven't really kept any copies of built older version. I'm only supporting the last two versions of VS, because they keep changing their packaging format, making it very hard to support old versions with one extension. But if you have an old machine with the old version you could maybe find the .vsix file there, I think they're kept in a folder somewhere, and just install that manually into your new computer.

**Comment by mattritchie** [comment]
Ah! I fixed it. 
I didn't notice your comment reply. So i tried that method out. 
I searched for the original vsix and couldn't find it. 
But found the directory where VS13 was using it. I copied that over to the new machine.
But that didn't appear.

I happened to be installing another extension and i noticed that it was prompting for an update of 1.8 to the latest. So something worked. I could then click "Enable". After a reboot the option is now there.

Thanks for your great plugin. We've got some dependencies that don't load in VS15-17-19 so we're stuck for the minute.
